
CREATE DATABASE StationeryShop
GO
USE StationeryShop;

CREATE TABLE Stationery
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
    [Type] NVARCHAR(50) NOT NULL,
    Quantity INT CHECK (Quantity >= 0) NOT NULL,
    Price FLOAT CHECK (Price >= 0) NOT NULL
);

CREATE TABLE Managers
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
    Surname NVARCHAR(50) NOT NULL,
    Age INT CHECK (Age >= 18) NOT NULL
);

CREATE TABLE Customers
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
);

CREATE TABLE Sellings
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    StationeryID INT FOREIGN KEY REFERENCES Stationery(ID) NOT NULL,
    ManagersID INT FOREIGN KEY REFERENCES Managers(ID) NOT NULL,
    CustomerID INT FOREIGN KEY REFERENCES Customers(ID) NOT NULL,
    CreatedAt DATETIME NOT NULL
);

CREATE TABLE StationeryArchive
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    StationeryID INT FOREIGN KEY REFERENCES Stationery(ID) NOT NULL,
    CreatedAt DATETIME NOT NULL
);

